### ISSUE TITLE
Create a docker container to run cron to update the extracted git repo

### ISSUE THREAD

**Issue by atoomic** [metacpan/metacpan-docker-production#18]
Several containers are going to use the shared volume to access to the metacpan_git_shared
The idea is to add a new docker container for running cron which will mount the git repo in rw and pull every X minutes/hours

```
      - type: volume
        source: metacpan_git_shared
        target: /shared/metacpan_git
        read_only: true

```

**Comment by ssoriche** [comment]
This issues is superseded by this pull request https://github.com/metacpan/metacpan-ansible/pull/24/files
